// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoAPI.Data;

namespace ProjetoAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220713144518_InserindoFilmes")]
    partial class InserindoFilmes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProjetoAPI.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Genero")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disponivel = true,
                            Genero = "Guerra",
                            Status = true,
                            Titulo = "O Resgate do Soldado Ryan"
                        },
                        new
                        {
                            Id = 2,
                            Disponivel = true,
                            Genero = "Drama",
                            Status = true,
                            Titulo = "Titanic"
                        },
                        new
                        {
                            Id = 3,
                            Disponivel = true,
                            Genero = "Comédia",
                            Status = true,
                            Titulo = "Gente Grande"
                        },
                        new
                        {
                            Id = 4,
                            Disponivel = true,
                            Genero = "Terror",
                            Status = true,
                            Titulo = "A Bruxa de Blair"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
